### ISSUE TITLE
libsvm error

### ISSUE THREAD

**Issue by aliammari1** [php-ai/php-ml-examples#6]
whenever i use the SVC in php-ml i got the next error always?
Fatal error: Uncaught Phpml\Exception\LibsvmCommandException: Failed running libsvm command: "C:\Users\aliam\Desktop\Web Project\We-Drive\View\vendor\php-ai\php-ml\bin\libsvm\svm-train.exe -s 0 -t 0 -c 1000 -n 0.500000 -d 3 -r 0 -p 0.100000 -m 100.000000 -e 0.001000 -h 1 -b 0 "C:\Users\aliam\Desktop\Web Project\We-Drive\View\vendor\php-ai\php-ml\var\phpml642e68b9e1e906.60547680" "C:\Users\aliam\Desktop\Web Project\We-Drive\View\vendor\php-ai\php-ml\var\phpml642e68b9e1e906.60547680-model"" with reason: "operable program or batch file." in C:\Users\aliam\Desktop\Web Project\We-Drive\View\vendor\php-ai\php-ml\src\SupportVectorMachine\SupportVectorMachine.php:163 Stack trace: #0 C:\Users\aliam\Desktop\Web Project\We-Drive\Controller\chatbot.php(33): Phpml\SupportVectorMachine\SupportVectorMachine->train(Array, Array) #1 {main} thrown in C:\Users\aliam\Desktop\Web Project\We-Drive\View\vendor\php-ai\php-ml\src\SupportVectorMachine\SupportVectorMachine.php on line 163

**Comment by SedraJadoua** [comment]
I have the same problem, were you find a solution ?

**Comment by SedraJadoua** [comment]
I have the same problem, did you find a solution ?
