### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by niksib** [php-ai/php-ml-examples#6]
Hello people.
I am a newbie in machine learning and I can't understand what output this example(languageDetection).
We input file with many sentences in three languages and result of this program its number like 1, what it is this number means?
Based on program name I think we need input some message and after complete, script show language of this sentence, but this is not true.

Can somebody describe how this script works and what it shows?

**Comment by linnoxlewis** [comment]
I'm interested too.

**Comment by itcraftsmanpl** [comment]
Hello, let me explain:
```php
echo 'Accuracy: '.Accuracy::score($randomSplit->getTestLabels(), $predictedLabels);
```
This number is accuracy of trained classifier. `1` means that `100%` predicted labels was correct.
Also in this examples you can see `StratifiedRandomSplit`. Class samples are split to two groups: train group and test group. Distribution of samples takes into account their targets and trying to divide them equally. You can adjust number of samples in each group.

This is most simple validation technique which allow you to test accuracy of trained model.

If this helps then please close the issue.

**Comment by niksib** [comment]
Does this mean that the accuracy of the language definition will be 100%?
Which way to look in order to implement input text from the console and after that program detects language?

**Comment by itcraftsmanpl** [comment]
Yes and no. Accuracy is 100% for given test data, this doesn't mean for all possible data.

To predict language you can use:
```php
$classifier->predict($samples);
```
But sample as `string` must be prepared:
`TokenCountVectorizer` - Transform a collection of text samples to a vector of token counts.
`TfIdfTransformer` - Tf–idf, short for term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus.

You can read more in:
http://php-ml.readthedocs.io/en/latest/machine-learning/feature-extraction/token-count-vectorizer/ 
http://php-ml.readthedocs.io/en/latest/machine-learning/feature-extraction/tf-idf-transformer/

**Comment by niksib** [comment]
`var_dump($classifier->predict($samples));`

This output array with languages and every key of this array correspond to sentence in langues.csv?

**Comment by mountainguan** [comment]
@niksib You can use `var_dump($vectorizer->getVocabulary());` to get all the split words.

**Comment by mountainguan** [comment]
@itcraftsmanpl I try to `new` both `TokenCountVectorizer` and `TfIdfTransformer`,then I put my unknown word to predict.It seems that **vectors can't be matching** in a proper way.If you have time,I hope a sample as string's example can be publish on here.Thanks for all your work for this project.

**Comment by akondas** [comment]
Hello @mountainguan, sorry for late response but I miss this issue. If have those examples then I can look at your problem. If not then maybe we can close issue?

**Comment by akondas** [comment]
https://github.com/Neroxiezi/PHP-ML-study - :open_mouth: I did not know about it. Amazing...
