### ISSUE TITLE
Example of a Quadratic formula

### ISSUE THREAD

**Issue by daniel-lucio** [php-ai/php-ml-examples#8]
would be awesome if you put an example of least-squares for the y = Ax²+Bx+C case please

**Comment by daniel-lucio** [comment]
NVM, I think I did it myself
http://inside-out.xyz/technology/n-order-linear-equations-curve-fit-with-least-squares-and-php.html

In case you wonder how.

**Comment by akondas** [comment]
Thanks for link :+1:
